### PR TITLE
Day17 activities

### PR DESCRIPTION
**Pull request by sharonjohnson007**
please review

### CODE REVIEW

**Review by dorarajgcit — COMMENTED** [review]
1. Why there are many empty lines after this line
public class CheckOddEven {

2. PrintDayInWord - Follow java coding standard.  The variable name daynumber is not following it.
int daynumber = 7;

3. PrintDayInWord - Uncomment the if block and indent the lines.

4. PrintDayInWord - There is a problem in switch statement.  Fix it.  Clue: Check its output for daynumber = 0

5. PrintNumberInWord - Uncomment the if block and indent the lines.

**Comment by sharonjohnson007** [comment]
sir please review now

**Review by dorarajgcit — COMMENTED** [review]
Remove the unwanted files

**Review by dorarajgcit — COMMENTED** [review]
Still some unwanted files are there...remove them.

**Review by dorarajgcit — COMMENTED** [review]
Remove the Day17.iml too.

**Review by dorarajgcit — COMMENTED** [review]
Remove unwanted files.

**Pull request merged**
